config/routes.rb
Rails.application.routes.draw do
  get 'calendario_acticvidades/index'
  get 'tareas_completadas/index'
  get 'registro_asistencias/index'
  get 'tareas_pendientes/index'
  devise_for :users
  get 'todas_tareas/index'
  resources :tareas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'todas_tareas#index'  # Define esta como la página principal
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'tareas_pendientes', to: 'tareas_pendientes#index'
  resources :todas_tareas
  resources :tareas_pendientes
  resources :tareas_completadas
  resources :calendario_acticvidades
  resources :registro_asistencias
  resources :empleados
  resources :tareas do
    member do
      patch :completar  # Ruta para marcar una tarea como completada
    end
  end
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  def index
    @empleados = User.all
    @empleado = User.new
    if params[:search].present?
      @empleados = User.where("nombre ILIKE :query OR numero_control ILIKE :query OR apellidos ILIKE :query", query: "%#{params[:search]}%")
                       .paginate(page: params[:page], per_page: 10)
    else
      @empleados = User.paginate(page: params[:page], per_page: 10)
    end
  end

  def edit
    @empleado = User.find(params[:id])
  end

  def create
    @empleado = User.new(empleado_params)
    if @empleado.save
      redirect_to empleados_path, notice: "Empleado registrado correctamente."
    else
      if params[:search].present?
        @empleados = User.where("nombre ILIKE :query OR apellidos ILIKE :query OR numero_control ILIKE :query", query: "%#{params[:search]}%")
                         .paginate(page: params[:page], per_page: 10)
      else
        @empleados = User.paginate(page: params[:page], per_page: 10)
      end
      render :index
    end
  end

  def update
    @empleado = User.find(params[:id])
    if @empleado.update(empleado_params)
      redirect_to empleados_path, notice: "Empleado actualizado correctamente."
    else
      @empleados = User.paginate(page: params[:page], per_page: 10)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @empleado = User.find(params[:id])
    @empleado.destroy
    redirect_to empleados_path, notice: "Empleado eliminado correctamente."
  end

  private

  def empleado_params
    params.require(:user).permit(:nombre, :apellidos, :email, :puesto, :phone_number, :hora_entrada, :hora_salida)
  end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/edit.html.erb
<!-- filepath: app/views/empleados/edit.html.erb -->
<div class="modal show d-block" tabindex="-1" aria-labelledby="modalEditarEmpleadoLabel" aria-modal="true" role="dialog" style="background: rgba(0,0,0,0.2);">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalEditarEmpleadoLabel"><%= t('tareas.acciones.editar') %></h5>
      </div>
      <div class="modal-body">
        <%= form_with(model: @empleado, url: empleado_path(@empleado), method: :patch, local: true) do |form| %>          <div class="mb-3">
            <%= form.label :nombre, "Nombre", class: "form-label" %>
            <%= form.text_field :nombre, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :apellidos, "Apellidos", class: "form-label" %>
            <%= form.text_field :apellidos, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :email, "Correo electrónico", class: "form-label" %>
            <%= form.email_field :email, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :puesto, "Puesto", class: "form-label" %>
            <%= form.text_field :puesto, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :phone_number, "Teléfono", class: "form-label" %>
           <%= form.text_field :phone_number, class: "form-control", maxlength: 10 %>
          </div>
          <div class="mb-3">
            <%= form.label :hora_entrada, "Hora de entrada", class: "form-label" %>
            <%= form.time_field :hora_entrada, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :hora_salida, "Hora de salida", class: "form-label" %>
            <%= form.time_field :hora_salida, class: "form-control" %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Guardar cambios", class: "btn btn-primary" %>
            <%= link_to "Cancelar", empleados_path, class: "btn btn-secondary text-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/empleados/index.html.erb
<div class="container mt-4">
  <div class="row align-items-center mb-4">
    <div class="col-md-4">
      <h2 class="mb-0">Empleados registrados</h2>
    </div>
    <div class="col-md-4">
      <%= form_with url: empleados_path, method: :get, local: true do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], placeholder: t("tareas.acciones.search"), class: "form-control" %>
          <button class="btn btn-primary" type="submit"><%= t("tareas.acciones.search") %></button>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 text-end">
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalNuevoEmpleado">
        Nuevo empleado
      </button>
    </div>
  </div>
  <!-- Tabla de empleados -->
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="table-primary">
        <tr>
          <th>Nombre</th>
          <th>Apellidos</th>
          <th>Correo electrónico</th>
          <th>Puesto</th>
          <th>Teléfono</th>
          <th>Número de control</th>
          <th>Hora entrada</th>
          <th>Hora salida</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @empleados.each do |empleado| %>
          <tr>
            <td><%= empleado.nombre %></td>
            <td><%= empleado.apellidos %></td>
            <td><%= empleado.email %></td>
            <td><%= empleado.puesto %></td>
            <td><%= empleado.phone_number %></td>
            <td><%= empleado.numero_control %></td>
            <td><%= empleado.hora_entrada&.strftime("%H:%M") if empleado.hora_entrada.present? %></td>
            <td><%= empleado.hora_salida&.strftime("%H:%M") if empleado.hora_salida.present? %></td>
            <td>
              <%= link_to t('tareas.acciones.editar'), edit_empleado_path(empleado), class: "btn btn-secondary text-light" %>
              <%= link_to t('tareas.acciones.eliminar'), empleado_path(empleado), method: :delete, data: { confirm: "Confirmar Elminación" }, class: "btn btn-danger text-light" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- Modal para nuevo empleado -->
  <div class="modal fade" id="modalNuevoEmpleado" tabindex="-1" aria-labelledby="modalNuevoEmpleadoLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalNuevoEmpleadoLabel">Registrar nuevo empleado</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
          <% if @empleado && @empleado.errors.any? %>
            <script>
              document.addEventListener('DOMContentLoaded', function() {
                var modal = new bootstrap.Modal(document.getElementById('modalNuevoEmpleado'));
                  modal.show();
              });
            </script>
          <% end %>
        </div>
        <div class="modal-body">
          <%= form_with(model: @empleado, url: empleados_path, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :nombre, "Nombre", class: "form-label" %>
              <%= form.text_field :nombre, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :apellidos, "Apellidos", class: "form-label" %>
              <%= form.text_field :apellidos, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :email, "Correo electrónico", class: "form-label" %>
              <%= form.email_field :email, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :puesto, "Puesto", class: "form-label" %>
              <%= form.text_field :puesto, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :phone_number, "Teléfono", class: "form-label" %>
              <%= form.text_field :phone_number, class: "form-control, maxlength: 10" %>
            </div>
            <div class="mb-3">
              <%= form.label :hora_entrada, "Hora de entrada", class: "form-label" %>
              <%= form.time_field :hora_entrada, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :hora_salida, "Hora de salida", class: "form-label" %>
              <%= form.time_field :hora_salida, class: "form-control" %>
            </div>
            <!--
            <div class="mb-3">
              <%= form.label :password, "Contraseña", class: "form-label" %>
              <%= form.password_field :password, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :password_confirmation, "Confirmar contraseña", class: "form-label" %>
              <%= form.password_field :password_confirmation, class: "form-control" %>
            </div>
            -->
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <%= form.submit "Registrar", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>